### ISSUE TITLE
Case insensitive property deserialization

### ISSUE THREAD

**Issue by Havunen** [Havunen/SystemTextJsonPatch#10]
Should this package follow `System.Text.Json.JsonSerializerOptions.PropertyNameCaseInsensitive` option for case sensitive deserialization of patch document, or is there any reason not to? relates to: https://github.com/Havunen/SystemTextJsonPatch/pull/9

**Comment by campersau** [comment]
If yes, then the deserializing of the operations could be improved for example like this: https://github.com/campersau/SystemTextJsonPatch/commit/4da8d3d21a88afd72f1cb223e4cae0f6bab79dd9 to get a little bit more performance:

|              Method |        Mean |     Error |     StdDev |      Median |  Gen 0 | Allocated |
|-------------------- |------------:|----------:|-----------:|------------:|-------:|----------:|
| SystemTextJsonPatch_base |    10.12 us |  0.192 us |   0.509 us |     9.887 us | 0.2747 |      4 KB |
| SystemTextJsonPatch_commit |     9.120 us |   0.1567 us |   0.2574 us |     9.085 us | 0.2441 |      3 KB |

**Comment by Havunen** [comment]
Done
