### ISSUE TITLE
Use Throw helpers for throwing exceptions

### ISSUE THREAD

**Issue by jmbryan4** [Havunen/SystemTextJsonPatch#21]
use the `ArgumentNullException.ThrowIfNull` throw helper where possible to improve performance. Available with .NET 6

see: https://devblogs.microsoft.com/dotnet/performance_improvements_in_net_7/#exceptions
source: https://github.com/dotnet/runtime/blob/main/src/libraries/System.Private.CoreLib/src/System/ArgumentNullException.cs#L67-L69

https://andrewlock.net/exploring-dotnet-6-part-11-callerargumentexpression-and-throw-helpers/#throw-helpers-in-c-

https://github.com/search?q=repo%3AHavunen%2FSystemTextJsonPatch%20throw%20new%20Argument&type=code
![image](https://github.com/Havunen/SystemTextJsonPatch/assets/37884221/44879a5c-e448-479c-8205-d0c1f7d70027)

**Comment by Havunen** [comment]
Hi, thanks for sharing. We shiuld implement this IMO

**Comment by Havunen** [comment]
This is now implemented in master branch and will be available in the next release. The change improved overall performance about 5%.
