### ISSUE TITLE
Throw new exception type when test operation fails

### ISSUE THREAD

**Issue by kipusoep** [Havunen/SystemTextJsonPatch#22]
Currently it's hard to distinguish between a failing test operation and other apply issues, because they all throw a `JsonPatchException`.
I would like to return a `409 Conflict` http status when a test operation fails, but the only way to identify this is by catching the exception and check if the message contains `" is not equal to the test value "`.
It would be nice if an exception of another type was thrown, for example a `JsonPatchTestOperationException`.

**Comment by Havunen** [comment]
Hi, thanks for the issue. I think this is great enhancement to this library but it needs to be done in the next major release

**Comment by Havunen** [comment]
Actually we could just extend the new exception type from `JsonPatchTestOperationException`

**Comment by kipusoep** [comment]
Isn't it a breaking change? If you currently catch the JsonPatchException, will it also catch if if the exception is of type JsonPatchTestOperationException?

**Comment by Havunen** [comment]
> Isn't it a breaking change? If you currently catch the JsonPatchException, will it also catch it if the exception is of type JsonPatchTestOperationException? 

yes. they both inherit from the same type, but you can also explicitly catch `JsonPatchTestOperationException` now. I also bumped the major version to v3 and mentioned the possible breaking change in changelog.

**Comment by kipusoep** [comment]
So I just updated to v3, but when I call `ApplyTo()` I still get a `JsonPatchException` instead of the new `JsonPatchTestOperationException`.

**Comment by kipusoep** [comment]
It seems to come from this: https://github.com/Havunen/SystemTextJsonPatch/blob/f6df1c15511d53e431e736f9c9f3259a3c724467/SystemTextJsonPatch/Internal/ErrorReporter.cs#L6

**Comment by Havunen** [comment]
This should work now in 3.0.1

**Comment by kipusoep** [comment]
For me it's not there yet. I have a unit test which tests a patch operation with a path that does not exist, I would assume it doesn't throw a `JsonPatchTestOperationException` but the good old `JsonPatchException` instead.
Because it's not a failing json patch test operation, it's just a replace operation instead.

**Comment by Havunen** [comment]
Ok, I need to check that

**Comment by Havunen** [comment]
I refactored the exception handling so that `JsonPatchTestOperationException` is now thrown only for test -operations failures, but FailedOperation properties are moved to `JsonPatchException` 

This change will be available in the next release
