### ISSUE TITLE
ERROR: value is invalid for target location

### ISSUE THREAD

**Issue by SihirliDev** [Havunen/SystemTextJsonPatch#28]
Hi there,

Thank you for this great library which saves us!

I have a User class which has a UserProfile property. UserProfile property has OnboardingStatus field. When I try to update the Onboarding status it throws error:

`SystemTextJsonPatch.Exceptions.JsonPatchTestOperationException: The value '{
                "OnboardingStatus": 1
            }' is invalid for target location.`

This is how I call the API:

```
{
    "Username": "test@sherleydev.com",
    "PatchDocument": [
        {
            "op": "replace",
            "path": "/UserProfile",
            "value": {
                "OnboardingStatus": 1
            }
        }
    ]
}
```

These are the classes for User and UserProfile:

```
public class User
{
	public Guid Id { get; set; }
	public required string ClerkUserId { get; set; }

	public UserProfile? UserProfile { get; set; }

	public ICollection<Organization> Organizations { get; } = new List<Organization>();
}


public class UserProfile
{
	public Guid Id { get; set; }

        public required string Username { get; set; }

	public required string FirstName { get; set; }
	public required string LastName { get; set; }

	public required string Email { get; set; }

        public required int OnboardingStatus { get; set; }

	public Guid UserId { get; set; }
	public User? User { get; set; }
}
```

Thank you for your assistance!

**Comment by Havunen** [comment]
Hi @SihirliDev 

Thanks for reporting the issue. 
I can try to take a look when time permits. 

If you want to speed up getting this fixed, could you please create a complete repro in a Github project or a zip file with complete source code. 

Thanks

**Comment by SihirliDev** [comment]
Hi again,

After investigating the problem so far, I could find that I didn't include the UserProfile property in my query. Added it, and it works.

So, there is no issue related to this package.

Thank you for your interest and have a wonderful day!
