### ISSUE TITLE
"JsonPatchTestOperationException: The value '1000' is invalid for target location." for nullable valuetype-props

### ISSUE THREAD

**Issue by Rgaroth** [Havunen/SystemTextJsonPatch#32]
Consider the following minimalistic test:

```
[Fact]
public void Test()
{
    Class1 obj = new();
    var sourcePatch = new JsonPatchDocument<Class1>().Replace(c => c.Id, 1000);
    var deserealizedPatch = JsonSerializer.Deserialize<JsonPatchDocument<Class1>>(JsonSerializer.Serialize(sourcePatch));

    sourcePatch.ApplyTo(obj); // success
    deserealizedPatch.ApplyTo(obj); // JsonPatchTestOperationException: The value '1000' is invalid for target location.
}

public class Class1
{
    public int? Id { get; set; }
}
```

When I try to patch a NULLABLE property by deserialized JsonPatchDocument, I get an error JsonPatchTestOperationException: The value '1000' is invalid for target location

**Comment by Havunen** [comment]
Hi,

This sounds like a bug. I will take a look

**Comment by Havunen** [comment]
The test case you provided here does not reproduce the error? Do you maybe have incorrect using statement or something similar in the real code?

**Comment by Havunen** [comment]
CI run also green: https://github.com/Havunen/SystemTextJsonPatch/commit/06aaa858171e986a02d6787449e32c0961eb84d1

**Comment by Rgaroth** [comment]
You're right, it doesn't repeat in a bare project... Actually, I found this error when I passed the patch object as the body of a POST request. If you make a controller method and pass a similar patch, will you also get an error?
