### ISSUE TITLE
Could you please to help me to make snake case path and value work?

### ISSUE THREAD

**Issue by sguryev** [Havunen/SystemTextJsonPatch#36]
I have added description to the [PR](https://github.com/Havunen/SystemTextJsonPatch/pull/35). There is the test showing my problem.

**Comment by Havunen** [comment]
This will be fixed in the next release. It will be breaking change

**Comment by sguryev** [comment]
@Havunen any workarounds we can use now? I think I can invent something but would like o know the best place to do it

**Comment by Havunen** [comment]
using `JsonPropertyAttribute` to decorate the snake_case property names everywhere you need it can be used as workaround, I will try to make a new release this weekend anyway

**Comment by sguryev** [comment]
Ouch, it looks too scary for our project :) I was thinking about some endpoint filter or middleware which can replace the body for PATCH requests

**Comment by Havunen** [comment]
v4.0.0 has been released https://github.com/Havunen/SystemTextJsonPatch/releases/tag/v4.0.0
